name: check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_constraints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash -l {0}
        run: nvm install
      - id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: |
          yarn install --immutable

      - name: check constraints
        run: |
          yarn run check:constraints

  check_typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash -l {0}
        run: nvm install
      - id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: |
          yarn install --immutable

      - name: check typing
        run: |
          yarn run check:typing

  check_linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash -l {0}
        run: nvm install
      - id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: |
          yarn install --immutable

      - name: check linting
        run: |
          yarn run check:linting

  check_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash -l {0}
        run: nvm install
      - id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: |
          yarn install --immutable

      - name: check formatting
        run: |
          yarn run check:formatting

  check_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash -l {0}
        run: nvm install
      - id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: |
          yarn install --immutable

      - name: test
        run: |
          yarn run test

  check_versioning:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - shell: bash -l {0}
        run: nvm install
      - id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: |
          yarn install --immutable

      - name: version
        run: |
          yarn version check
